version: 2
jobs:
  build:
    working_directory: ~/yoga2
    docker:
      # Node 10 LTS
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - run:
          name: install-package-dependencies
          command: yarn run bootstrap:ci
      - run:
          name: link yoga
          workdir: ./packages/yoga
          command: sudo npm link --unsafe-perm=true
      - run:
          name: run-build
          command: sudo yarn run build:ci
      - run:
          name: run lint
          command: yarn run lint
